### ISSUE TITLE
Milestone1 feedback

### ISSUE THREAD

**Issue by ArmaghanSarvar** [UBC-MDS/nba_player_stat#26]
Congratulations on finishing milestone 1! We can see you put a lot of work into this project, nice work! Below we list some specific feedback you can use to improve your project.

Section 1: Motivation and purpose: writing: 2/2, reasoning: 8/8
- Great details can be provided on what the application visualizations will show.

Section 2: Description of data: writing: 2/2, reasoning: 7/8
- The variables have been explained in detail; however, evident exploratory data analysis is not added (for example how many null/missing values does each variable have?)

Section 3: Research questions and usage scenarios: writing: 2/2, reasoning: 7/12
- The level of detail provided in the persona description is poor, the number of words it is less than 200-300 words.

Section 4: Description of the app and sketch: viz: 10/10, writing: 2/2, reasoning: 3/3

Section 5: Teamwork contract and collaborative documentation: reasoning: 4/4

Section 6: Code of conduct: 1/1

Section 7: Contribution guidelines: 1/1

If anything is unclear, please feel free to ask questions. Great work!

**Comment by ArmaghanSarvar** [comment]
Hi @pengzh313,
Yes, according to the rubric of Milestone 1, more details were required for the usage scenario as it is essential before implementing the app. 
Thank you very much for editing the persona section and including the link here. This will definitely help you have a better idea of the app requirements while completing the tasks along the way. However, unfortunately, I do not think the grade can be changed after the deadline.

**Comment by pengzh313** [comment]
Hi @ArmaghanSarvar ,
Thank you for the reply.
Regarding the milestone 1 grade, I believe it has not be published yet. On behalf of our team members, I would ask you and the instructor if the point deduction could be re-considered.

It seems the Milestone 1 instruction dose not indicate the "min 200-300 words" requirement for the Section 3: Research questions and usage scenarios (I guess it might be included in the detailed rubric somewhere else). Usually the minimum number of words in an instruction would be more straightforward to draw attentions from people who are going to response the documentation writing tasks in which level of detailing. 

In addition, I think the main purpose of this persona writing practice is to reflect if the learner understands who is the target audience and describe how the app can meet the audience's needs in the specific case. With regard to how to write the persona section, it is true that students should follow the instruction and example as close as possible since this is kinda of like an industrial standard already. But for people who had never been exposed in this industry before, it is very likely they will make a different face of the document but most of the key functionalities have been covered. Based on my initial interpretation on the instruction/example and my usual writing style (I like everything briefly and to the point as we all are in a fast paced working environment), I prepared a version of the usage scenarios that has been also reviewed by other team members before submitting the milestone 1. So we do have a big confusion to receive a 7/12  evaluation for this part. 

As you can see, we made a quick update on the usage scenarios to let the document more close to the standard style and meet the min words requirement as per the specific feedback. Our intention is not to ask regrading the updated version after the deadline, but to demonstrate an additional example of our learning outcome. We hope this could be considered if it is reasonable to change the 7/12 evaluation.

Thank you for your time to review the case.

**Comment by ArmaghanSarvar** [comment]
Hi, 
I have changed your grade for this section to 9/12.
Thank you.

**Comment by Suraporn** [comment]
Close for ML2 submission.
